PROGRAM MAIN
	IMPLICIT NONE
	INTERFACE
		RECURSIVE FUNCTION F(N) RESULT(M)
			IMPLICIT NONE
			INTEGER,INTENT(IN)::N
			INTEGER::M
		END FUNCTION F
	END INTERFACE
	INTEGER::N,I
	PRINT*,'请输入N的数值：'
	READ*,N
	DO I=0,N
		PRINT*,F(I)
	END DO
END PROGRAM MAIN
RECURSIVE FUNCTION F(N) RESULT(M)
	IMPLICIT NONE
	INTEGER,INTENT(IN)::N
	INTEGER::M
	IF(N==0)THEN
		M=0
	ELSEIF(N==1)THEN
		M=1
	ELSEIF(N>=2)THEN
		M=F(N-1)+F(N-2)
	ENDIF
END FUNCTION F